export { presetsColor }
export { presetsPerspective }
export { perspectiveDefault }
export { colorsDefault }

import { type Colors } from '../Hammer'

/*
  metalBottom: ['red', 'red'],
  wood: 'red',
*/

const colorsDefault: Colors = {
  metalCorner: 'red',
  metalSlope: '#959595',
  metalFace: 'red',
  metalTop: 'red',
  metalBottom2: 'red',
  metalBottom: ['#9f9f9f', '#7a7a7a'],
  wood: ['#e69d00', '#9b4818'],
  lightningBolt: ['#ffff00', '#ffb300'],
  colorSlopeTop: ['#bcbcbc', '#9a9a9a'],
  colorSlopeLeft: '#b8b8b8',
  colorSlopeRight: '#8a8a8a',
  colorSlopeTopRight: '#afafaf',
  colorSlopeBottom: ['#9a9a9a', '#696969'],
  colorFaceRight: '#7a7a7a',
  colorFaceUpper: ['#a8a8a8', '#838181'],
  colorFaceFront: ['#aaaaaa', '#7e7e7e'],
  colorCornerTopLeft: '#c8c8c8',
  colorCornerTopRight: '#a8a8a8',
  colorCornerBottomRight: '#707070',
  colorCornerBottomLeft: '#bababa',
}

const perspectiveDefault: Perspective = {
  rotation2D: 0,
  handleDiameter: 7.7,
  handleLength: 12.4,
  rotate: { x: 0.00, y: -7.16, z: -2 },
}

type Perspective = {
  rotation2D: number
  rotate: { x: number; y: number; z: number }
  handleDiameter?: number
  handleLength?: number
}


const presetsColor: Record<string, Colors> = {
  'colors-default': { ...colorsDefault },
  gradientTmp: {
    metalCorner: 'red',
    metalSlope: '#a6a6a6',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#878787'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffb300'],
    colorSlopeTop: ['#d1d1d1', '#ababab'],
    colorSlopeLeft: '#cccccc',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#c2c2c2',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#bababa', '#929090'],
    colorFaceFront: ['#bdbdbd', '#8c8c8c'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#bababa',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#cfcfcf',
  },
  gradientBoring: {
    metalCorner: 'red',
    metalSlope: '#a6a6a6',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#878787'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffa300'],
    colorSlopeTop: ['#c2c2c2', '#ababab'],
    colorSlopeLeft: '#c4c4c4',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#b0b0b0',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#b3b3b3', '#929090'],
    colorFaceFront: ['#b8b8b8', '#8c8c8c'],
    colorCornerTopLeft: '#cfcfcf',
    colorCornerTopRight: '#bababa',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#c4c4c4',
  },
  gradient12: {
    metalCorner: 'red',
    metalSlope: '#a6a6a6',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#878787'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffc000'],
    colorSlopeTop: ['#c9c9c9', '#ababab'],
    colorSlopeLeft: '#cccccc',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#c2c2c2',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#bababa', '#929090'],
    colorFaceFront: ['#bdbdbd', '#8c8c8c'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#bababa',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#cfcfcf',
  },
  gradient11: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#878787'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffc000'],
    colorSlopeTop: ['#c9c9c9', '#ababab'],
    colorSlopeLeft: '#cccccc',
    colorSlopeRight: '#a3a3a3',
    colorSlopeTopRight: '#a3a3a3',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#bababa', '#929090'],
    colorFaceFront: ['#bdbdbd', '#8c8c8c'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#b5b5b5',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#cfcfcf',
  },
  gradient10: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#878787'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffc000'],
    colorSlopeTop: ['#dedede', '#ababab'],
    colorSlopeLeft: '#d1d1d1',
    colorSlopeRight: '#a3a3a3',
    colorSlopeTopRight: '#a3a3a3',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#c2c2c2', '#929090'],
    colorFaceFront: ['#c9c9c9', '#8c8c8c'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#b5b5b5',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#cfcfcf',
  },
  gradient9: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#bababa', '#8f8f8f'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffdd00'],
    colorSlopeTop: ['#d9d9d9', '#b8b8b8'],
    colorSlopeLeft: '#d9d9d9',
    colorSlopeRight: '#adadad',
    colorSlopeTopRight: '#b3b3b3',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#949494',
    colorFaceUpper: ['#c2c2c2', '#9e9e9e'],
    colorFaceFront: ['#cccccc', '#949494'],
    colorCornerTopLeft: '#ededed',
    colorCornerTopRight: '#c2c2c2',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#dbdbdb',
  },
  gradient8: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#bababa', '#8f8f8f'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffdd00'],
    colorSlopeTop: ['#ededed', '#c2c2c2'],
    colorSlopeLeft: '#f5f5f5',
    colorSlopeRight: '#ababab',
    colorSlopeTopRight: '#dcdbdb',
    colorSlopeBottom: ['#ababab', '#757575'],
    colorFaceRight: '#878787',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#cccccc', '#949494'],
    colorCornerTopLeft: '#f2f2f2',
    colorCornerTopRight: '#cfcfcf',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#d1d1d1',
  },
  gradient7: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#b0b0b0', '#6b6b6b'],
    wood: ['#ffae00', '#ac501b'],
    lightningBolt: ['#ffff00', '#ffff00'],
    colorSlopeTop: ['#ededed', '#c2c2c2'],
    colorSlopeLeft: '#f5f5f5',
    colorSlopeRight: '#9e9e9e',
    colorSlopeTopRight: '#dcdbdb',
    colorSlopeBottom: ['#ababab', '#6b6b6b'],
    colorFaceRight: '#828282',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#cccccc', '#8c8c8c'],
    colorCornerTopLeft: '#f2f2f2',
    colorCornerTopRight: '#cfcfcf',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#d1d1d1',
  },
  gradient6: {
    metalCorner: 'red',
    metalSlope: '#e3e3e3',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#d4d4d4', '#6b6b6b'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffff00', '#ffff00'],
    colorSlopeTop: ['#ededed', '#c2c2c2'],
    colorSlopeLeft: '#d1d1d1',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#dcdbdb',
    colorSlopeBottom: ['#b8b8b8', '#8a8a8a'],
    colorFaceRight: '#616161',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#cccccc', '#8c8c8c'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#cfcfcf',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#dedede',
  },
  gradient5: {
    metalCorner: 'red',
    metalSlope: '#a8a8a8',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#d6d6d6', '#949494'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffff00', '#ffdf00'],
    colorSlopeTop: ['#dedede', '#c4c4c4'],
    colorSlopeLeft: '#d1d1d1',
    colorSlopeRight: '#9e9e9e',
    colorSlopeTopRight: '#dcdbdb',
    colorSlopeBottom: ['#b8b8b8', '#8a8a8a'],
    colorFaceRight: '#ababab',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#d9d9d9', '#b0afaf'],
    colorCornerTopLeft: '#dedede',
    colorCornerTopRight: '#cfcfcf',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#dedede',
  },
  gradient4: {
    metalCorner: 'red',
    metalSlope: '#a8a8a8',
    metalFace: 'red',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: ['#d6d6d6', '#949494'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffde05', '#ffb514'],
    colorSlopeTop: ['#e6e6e6', '#c4c4c4'],
    colorSlopeLeft: '#ebebeb',
    colorSlopeRight: '#9e9e9e',
    colorSlopeTopRight: '#d9d9d9',
    colorSlopeBottom: ['#b8b8b8', '#8a8a8a'],
    colorFaceRight: '#ababab',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#d6d6d6', '#b0afaf'],
    colorCornerTopLeft: '#ededed',
    colorCornerTopRight: '#cfcfcf',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#d6d6d6',
  },
  gradient3: {
    metalCorner: '#c0c0c0',
    metalSlope: '#a8a8a8',
    metalFace: ['#d8d8d8', '#bfbfbf'],
    metalTop: 'rgba(0,0,0,0.2)',
    metalBottom2: '#909090',
    metalBottom: ['#d6d6d6', '#949494'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffe507', '#ffc212'],
    colorSlopeTop: ['#e6e6e6', '#bfbfbf'],
    colorSlopeLeft: '#dedede',
    colorSlopeRight: '#9e9e9e',
    colorSlopeTopRight: '#d9d9d9',
    colorSlopeBottom: ['#c7c7c7', '#909090'],
    colorFaceRight: '#ababab',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#d6d6d6', '#b0afaf'],
    colorCornerTopLeft: '#ededed',
    colorCornerTopRight: '#b0b0b0',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#d6d6d6',
  },
  gradient2: {
    metalCorner: '#c0c0c0',
    metalSlope: '#a8a8a8',
    metalFace: ['#d8d8d8', '#bfbfbf'],
    metalTop: 'rgba(0,0,0,0.2)',
    metalBottom2: '#909090',
    metalBottom: ['#d6d6d6', '#949494'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffe507', '#ffc212'],
    colorSlopeTop: ['#dedede', '#c7c7c7'],
    colorSlopeLeft: '#cccccc',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#d9d9d9',
    colorSlopeBottom: ['#c7c7c7', '#909090'],
    colorFaceRight: '#a2a2a3',
    colorFaceUpper: ['#cfcfcf', '#a8a8a8'],
    colorFaceFront: ['#d6d6d6', '#b0afaf'],
    colorCornerTopLeft: '#cacbcb',
    colorCornerTopRight: '#b0b0b0',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#bfbfbf',
  },
  gradient1: {
    metalCorner: '#c0c0c0',
    metalSlope: '#a8a8a8',
    metalFace: ['#d8d8d8', '#bfbfbf'],
    metalTop: 'rgba(0,0,0,0.2)',
    metalBottom2: '#909090',
    metalBottom: ['#d6d6d6', '#949494'],
    wood: ['#ffb152', '#aa5422'],
    lightningBolt: ['#ffe507', '#ffc212'],
    colorSlopeTop: ['#d6d6d6', '#c2c2c2'],
    colorSlopeLeft: '#c1c2c2',
    colorSlopeRight: '#999999',
    colorSlopeTopRight: '#d9d9d9',
    colorSlopeBottom: ['#b0b0b0', '#909090'],
    colorFaceRight: '#a2a2a3',
    colorFaceUpper: ['#bababa', '#a8a8a8'],
    colorFaceFront: ['#c7cac9', '#b0afaf'],
    colorCornerTopLeft: '#cacbcb',
    colorCornerTopRight: '#b0b0b0',
    colorCornerBottomRight: '#7d7d7d',
    colorCornerBottomLeft: '#979697',
  },
  vivid: {
    metalCorner: 'cyan',
    metalSlope: 'red',
    metalFace: 'blue',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: 'gray',
    wood: 'black',
    lightningBolt: 'black',
    colorSlopeTop: 'green',
    colorSlopeLeft: 'yellow',
    colorSlopeRight: 'orange',
    colorSlopeTopRight: 'navy',
    colorSlopeBottom: 'pink',
    colorFaceRight: 'blue',
    colorFaceUpper: 'purple',
    colorFaceFront: 'darkblue',
    colorCornerTopLeft: 'lime',
    colorCornerTopRight: 'magenta',
    colorCornerBottomRight: 'teal',
    colorCornerBottomLeft: 'gold',
  },
  modern: {
    metalCorner: '#bababa',
    metalSlope: '#ababab',
    metalFace: '#8c8c8c',
    metalTop: 'red',
    metalBottom2: 'red',
    metalBottom: '#878787',
    wood: '#96511d',
    lightningBolt: ['#ffff00', '#ffc000'],
  },
  'colors-default-previous': {
    metalCorner: '#ababab',
    metalSlope: '#949494',
    metalFace: '#757575',
    metalTop: '#6e6e6e',
    metalBottom2: '#7a7a7a',
    metalBottom: '#828282',
    wood: '#91512b',
    lightningBolt: '#fbbf28',
  },
  previous: {
    metalCorner: '#b5b5b5',
    metalSlope: '#949494',
    metalFace: '#757575',
    metalTop: '#6e6e6e',
    metalBottom2: '#767676',
    metalBottom: '#828282',
    wood: '#91512b',
    lightningBolt: '#f7bc26',
  },
  darker: {
    metalCorner: '#a3a3a3',
    metalSlope: '#8f8f8f',
    metalFace: '#757575',
    metalTop: '#878787',
    metalBottom2: '#878787',
    metalBottom: '#808080',
    wood: '#91512b',
    lightningBolt: '#f7bc26',
  },
  older2: {
    metalCorner: '#b0b0b0',
    metalSlope: '#949494',
    metalFace: '#757575',
    metalTop: '#878787',
    metalBottom2: '#878787',
    metalBottom: '#808080',
    wood: '#91512b',
    lightningBolt: '#f7bc26',
  },
  older: {
    metalCorner: '#b5b5b5',
    metalSlope: '#949494',
    metalFace: '#757575',
    metalTop: '#787878',
    metalBottom2: '#787878',
    metalBottom: '#707070',
    wood: '#91512b',
    lightningBolt: '#f7bc26',
  },
  brighter: {
    metalCorner: '#b5b5b5',
    metalSlope: '#949494',
    metalFace: '#7a7a7a',
    metalTop: '#787878',
    metalBottom2: '#787878',
    metalBottom: '#7a7a7a',
    wood: '#91512b',
    lightningBolt: '#f7bc26',
  },
  ['too-bright']: {
    metalCorner: '#bdbdbd',
    metalSlope: '#b3b3b3',
    metalFace: '#a6a6a6',
    metalTop: '#9e9e9e',
    metalBottom2: '#9e9e9e',
    metalBottom: '#a6a6a6',
    wood: '#a56c4a',
    lightningBolt: '#fbcc56',
  },
  oldest: {
    metalCorner: '#949494',
    metalSlope: '#828282',
    metalFace: '#696969',
    metalTop: '#707070',
    metalBottom2: '#707070',
    metalBottom: '#696969',
    wood: '#96511d',
    lightningBolt: '#ecb018',
  },
}

const presetsPerspective: Record<string, Perspective> = {
  'perspective-default': perspectiveDefault,
  previous: {
    rotation2D: 0,
    handleDiameter: 7.7,
    handleLength: 15,
    rotate: { x: 0.00, y: -7.16, z: -2 },
  },
  maud: {
    rotation2D: 0,
    handleLength: 10,
    rotate: { x: -0.1, y: -7, z: -2 },
  },
  old: {
    rotation2D: 0,
    rotate: { x: -0.13, y: -6.63, z: -1.2 },
  },
  ['old-long-handle']: {
    rotation2D: 0,
    handleLength: 20.5,
    rotate: { x: -0.13, y: -6.63, z: -1.2 },
  },
  ['old-mirrored']: {
    rotation2D: -21,
    rotate: { x: -0.7, y: 7.1, z: 0 },
  },
  previous1: {
    rotation2D: 11,
    rotate: { x: -0.3, y: -6.63, z: 0 },
  },
  previous2: {
    rotation2D: 13,
    rotate: { x: -0.4, y: 23.5, z: 0 },
  },
  new1: {
    rotation2D: -23,
    rotate: { x: -0.4, y: 152.8, z: 0 },
  },
  new2: {
    rotation2D: -23,
    rotate: { x: -0.6, y: 159.19, z: 0 },
  },
  new3: {
    rotation2D: -23,
    rotate: { x: -0.4, y: 159.3, z: 0 },
  },
  favicon: {
    rotation2D: 29,
    rotate: { x: -0.4, y: 0.6, z: 0 },
  },
  latest: {
    rotation2D: -30,
    rotate: { x: -0.5, y: 23.2, z: 0 },
  },
  ['vertical-mirrored']: {
    handleDiameter: 8.2,
    handleLength: 21.8,
    rotation2D: 0,
    rotate: { x: -0.4, y: -56.41, z: 0 },
  },
  vertical: {
    handleDiameter: 8.2,
    handleLength: 21.8,
    rotation2D: 0,
    rotate: { x: -0.4, y: -55.6, z: 0 },
  },
  laying: {
    handleDiameter: 8.5,
    handleLength: 20.9,
    rotation2D: 66.3,
    rotate: { x: -0.4, y: -56.41, z: 0 },
  },
}
